import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";


// The BLMelody-Light.otf file is missing, causing a build error. 
// Temporarily remove the problematic entry to allow successful build.

const blMelody = localFont({
  variable: "--font-bl-melody",
  display: "swap",
  src: [
    { path: "../assets/fonts/bl-melody/BLMelody-ExtraLight.otf", weight: "200", style: "normal" },
    { path: "../assets/fonts/bl-melody/BLMelody-Light.otf", weight: "300", style: "normal" },
    { path: "../assets/fonts/bl-melody/BLMelody-Regular.otf", weight: "400", style: "normal" },
    { path: "../assets/fonts/bl-melody/BLMelody-Medium.otf", weight: "500", style: "normal" },
    { path: "../assets/fonts/bl-melody/BLMelody-SemiBold.otf", weight: "600", style: "normal" },
    { path: "../assets/fonts/bl-melody/BLMelody-Bold.otf", weight: "700", style: "normal" },
  ],
});

const manrope = localFont({
  variable: "--font-manrope",
  display: "swap",
  src: [
    { path: "../assets/fonts/manrope/Manrope-VariableFont_wght.ttf", weight: "200 800", style: "normal" },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${blMelody.variable} ${manrope.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}